---
title: "US Hardware Regression"
author: "Nate Cox"
date: "2023-02-01"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(corrplot)  
library(bestglm)  
library(car) 
library(glmnet)
library(gridExtra)
library(caret)
library(sjmisc)
library(lubridate)
library(ggfortify)
library(readxl)
```

```{r}
econ <- read.csv('Indicators_edit.csv') %>%
  rename("Date" = "Year") %>%
  select(2,9:14)

hardware <- read.csv('USA_Sales_vs_CCI_by_year.csv') %>%
  rename("Date" = "year.TIME.",
         "Hardware" = "Tot",
         "CCI" = "Cci") %>%
  mutate(Hardware = as.numeric(Hardware)) 

omnibus_US <-right_join(econ, hardware, by = "Date") %>%
  mutate(`Inflation %` = as.numeric(`US.Inflation..annual...`),
         `GDP pc growth %` = as.numeric(`US.GDP.per.capita.growth..annual...`),
         `GDP pc` = as.numeric(`US.GDP.per.capita`),
         `Lending interest rate` = as.numeric(`US.Lending.interest.rate....`),
         `Unemployment` = as.numeric(`US.Unemployment`),
         `CPI` = as.numeric(`US.Consumer.price.index`),
         `CCI` = as.numeric(CCI)) %>%
  select(9:15,8)
omnibus_US$`Inflation %`[18] <- 7
omnibus_US$`Inflation %`[19] <- 6.5
omnibus_US$CCI[19] <- 97.1833333333
omnibus_US$`GDP pc growth %`[18] <- 5.7
omnibus_US$`GDP pc growth %`[19] <- 8.60
omnibus_US$`GDP pc`[18] <- 69227.11
omnibus_US$`GDP pc`[19] <- 75179.59
omnibus_US$`Lending interest rate`[18] <- 3.25
omnibus_US$`Lending interest rate`[19] <- 4.25
omnibus_US$Unemployment[18] <- 3.9
omnibus_US$Unemployment[19] <- 3.5
omnibus_US$CPI[18] <- 107
omnibus_US$CPI[19] <- 113.955
omnibus_USi <- omnibus_US 

```
#Interesting Graphs

#Exploratory Data Analysis


```{r}
scat_CCI <- ggplot(data = omnibus_USi) +
  geom_jitter(mapping = aes(x = Hardware/1000000, y = CCI )) +
  xlab("Hardware (mil)") +
  theme(aspect.ratio = 1)
scat_Inflation <- ggplot(data = omnibus_USi) +
  geom_jitter(mapping = aes(x = Hardware/1000000, y = `Inflation %`)) +
  xlab("Hardware (mil)") +
  theme(aspect.ratio = 1)
scat_GDPgrowth <- ggplot(data = omnibus_USi) +
  geom_jitter(mapping = aes(x = Hardware/1000000, y = `GDP pc growth %`)) +
  xlab("Hardware (mil)") +
  theme(aspect.ratio = 1)
scat_GDP <- ggplot(data = omnibus_USi) +
  geom_jitter(mapping = aes(x = Hardware/1000000, y = `GDP pc`)) +
  xlab("Hardware (mil)") +
  theme(aspect.ratio = 1)
scat_InterestRate <- ggplot(data = omnibus_USi) +
  geom_jitter(mapping = aes(x = Hardware/1000000, y = `Lending interest rate`)) +
  xlab("Hardware (mil)") +
  ylab("Lending interest rate %") +
  theme(aspect.ratio = 1)
scat_Unemployment <- ggplot(data = omnibus_USi) +
  geom_jitter(mapping = aes(x = Hardware/1000000, y = Unemployment)) +
  xlab("Hardware (mil)") +
  theme(aspect.ratio = 1)
scat_CPI <- ggplot(data = omnibus_USi) +
  geom_jitter(mapping = aes(x = Hardware/1000000, y = CPI)) +
  xlab("Hardware (mil)") +
  theme(aspect.ratio = 1)


grid.arrange(scat_CCI, scat_Inflation, scat_GDP, scat_GDPgrowth, scat_InterestRate, scat_Unemployment, scat_CPI, ncol =3)
```

```{r}
oUSi_cor <- cor(omnibus_USi %>% select(8,1:7))
corrplot(oUSi_cor, type = "upper",
         method ="number",
         tl.col = "black", tl.srt = 50) +
  theme(aspect.ratio = 1)
```

##Variable Selection

```{r}
oUSi_x <- as.matrix(omnibus_USi[, 1:7])
oUSi_y <- as.matrix(omnibus_USi[, 8])
oUSi_Elnet <- cv.glmnet(x = oUSi_x,
                        y = oUSi_y, 
                        type.measure = "mse", 
                        alpha = .5)  
#oUSi_Elnet$lambda.min
#oUSi_Elnet$lambda.1se

coef(oUSi_Elnet, s = "lambda.min")
coef(oUSi_Elnet, s = "lambda.1se")

bestsub_bic <- bestglm(omnibus_USi %>% select(1:8),
                        IC = "BIC",
                        method = "exhaustive")
summary(bestsub_bic$BestModel)
```

#Check For Interaction

```{r}
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + CCI:`GDP pc growth %`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + CCI:Unemployment, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + Unemployment:`GDP pc growth %`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + CCI:Unemployment:`GDP pc growth %`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + CCI:`GDP pc growth %` + CCI:Unemployment, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + CCI:`GDP pc growth %` + Unemployment:`GDP pc growth %`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + Unemployment:`GDP pc growth %` + CCI:Unemployment, data = omnibus_USi))

summary(lm(Hardware ~ CCI + `GDP pc` + `Lending interest rate` + CCI:`GDP pc`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc` + `Lending interest rate` + CCI:`Lending interest rate`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc` + `Lending interest rate` + `GDP pc`:`Lending interest rate`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc` + `Lending interest rate` + `GDP pc`:`Lending interest rate` + CCI:`GDP pc`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc` + `Lending interest rate` + CCI:`GDP pc`:`Lending interest rate`, data = omnibus_USi))
summary(lm(Hardware ~ CCI + `GDP pc` + `Lending interest rate` + CCI:`GDP pc` + CCI:`GDP pc`:`Lending interest rate`, data = omnibus_USi))
```

#Liniar Model

```{r}
#omnibus_USi_lm <- lm(Hardware ~ CCI + `GDP pc` + `Lending interest rate` + CCI:`GDP pc`, data = omnibus_USi)
omnibus_USi_lm <- lm(Hardware ~ CCI + `GDP pc growth %` + Unemployment + Unemployment:`GDP pc growth %` + CCI:Unemployment, data = omnibus_USi)
omnibus_USi$residuals <- omnibus_USi_lm$residuals
omnibus_USi$fitted <- omnibus_USi_lm$fitted.values
summary(omnibus_USi_lm)
```

#Assumptions

```{r}
#crPlots(omnibus_USi_lm)

avPlots(omnibus_USi_lm)

autoplot(omnibus_USi_lm, which = 2, ncol = 1, nrow = 1) + 
  theme(aspect.ratio = 1)

ggplot(omnibus_USi) + 
  geom_boxplot(mapping = aes(x = Hardware, y = residuals))+ 
  theme(aspect.ratio = 1)

autoplot(omnibus_USi_lm, which = 1, ncol = 1, nrow = 1) +
  theme(aspect.ratio = 1)

ggplot(data = omnibus_USi) + 
  geom_histogram(mapping = aes(x = residuals, y = ..density..), 
                 binwidth = 3500000) +
  stat_function(fun = dnorm, 
                color = "red", 
                linewidth = 2,
                args = list(mean = mean(omnibus_USi$residuals), 
                            sd = sd(omnibus_USi$residuals))) +
  theme(aspect.ratio = 1)
```

#Influential Points

```{r}
plot(cooks.distance(omnibus_USi_lm))
omnibus_USi$dffits <- dffits(omnibus_USi_lm)

ggplot(data = omnibus_USi) + 
  geom_point(mapping = aes(x = as.numeric(rownames(omnibus_USi)), 
                           y = abs(dffits))) +
  ylab("Absolute Value of DFFITS for Y") +
  xlab("Observation Number") +
  geom_hline(mapping = aes(yintercept = 2 * sqrt(length(omnibus_USi_lm$coefficients) /
                                                   length(dffits))),
             color = "red", 
             linetype = "dashed") +
  theme(aspect.ratio = 1)
```

#Inference

```{r}
confint(omnibus_USi_lm)
newdata = data.frame(CCI = 98.94, `GDP pc growth %` = 0.2, `Unemployment`= 4.6)%>%
  rename("GDP pc growth %" = "GDP.pc.growth..")
predict(omnibus_USi_lm, newdata = newdata, interval = "confidence")
```
